Loiloc/Controllers/Admin/Guarantee/GuaranteeadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Loiloc.Models;
using PagedList;
using PagedList.Mvc;
using System.Globalization;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
namespace Loiloc.Views.Guarantee
{
    public class GuaranteeadController : Controller
    {
        //
        // GET: /Guaranteead/
        private LoilocContext db = new LoilocContext();
        public ActionResult Index(FormCollection collection,string idCate)
        {
            List<SelectListItem> carlist = new List<SelectListItem>();

            var menuModel = db.tblManufactures.Where(m => m.Active == true).OrderBy(m => m.id).ToList();
            carlist.Clear();
            foreach (var item in menuModel)
            {
                carlist.Add(new SelectListItem { Text = item.Name, Value = item.id.ToString() });
            }
            if(idCate!=null && idCate!="")
            {
                ViewBag.drMenu = new SelectList(carlist, "Value", "Text",idCate);
            }
            else
            {
                ViewBag.drMenu = new SelectList(carlist, "Value", "Text");
            }
                 
            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            if (ClsCheckRole.CheckQuyen(14, 0, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
              
                if (Session["Thongbao"] != null && Session["Thongbao"] != "")
                {

                    ViewBag.thongbao = Session["Thongbao"].ToString();
                    Session["Thongbao"] = "";
                }
                if (collection["btnDelete"] != null)
                {
                    foreach (string key in Request.Form.Keys)
                    {
                        var checkbox = "";
                        if (key.StartsWith("chk_"))
                        {
                            checkbox = Request.Form["" + key];
                            if (checkbox != "false")
                            {
                                if (ClsCheckRole.CheckQuyen(14, 3, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
                                {
                                    int ids = Convert.ToInt32(key.Remove(0, 4));
                                    tblGuarantee tblGuarantee = db.tblGuarantees.Find(ids);
                                    db.tblGuarantees.Remove(tblGuarantee);
                                    db.SaveChanges();
                                    return RedirectToAction("Index");
                                }
                                else
                                {
                                    return Redirect("/Users/Erro");

                                }
                            }
                        }
                    }
                }
                return View();
            }
            else
            {
                return Redirect("/Users/Erro");

            }
        }
        public PartialViewResult partialGuarantee(int? page, string id,string idCate)
        {
            int ids = int.Parse(id);

            var ListQuarantee = db.tblGuarantees.Where(p => p.idDistrict == ids).ToList();
            if (idCate != null && idCate != "")
            {
                ViewBag.idCate = idCate;
                int idCates = int.Parse(idCate);
                ListQuarantee = ListQuarantee.Where(p => p.idManu == idCates).ToList();
            }

            const int pageSize = 20;
            var pageNumber = (page ?? 1);
            // Thiết lập phân trang
            var ship = new PagedListRenderOptions
            {
                DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                DisplayLinkToLastPage = PagedListDisplayMode.Always,
                DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                DisplayLinkToNextPage = PagedListDisplayMode.Always,
                DisplayLinkToIndividualPages = true,
                DisplayPageCountAndCurrentLocation = false,
                MaximumPageNumbersToDisplay = 5,
                DisplayEllipsesWhenNotShowingAllPageNumbers = true,
                EllipsesFormat = "&#8230;",
                LinkToFirstPageFormat = "Trang đầu",
                LinkToPreviousPageFormat = "«",
                LinkToIndividualPageFormat = "{0}",
                LinkToNextPageFormat = "»",
                LinkToLastPageFormat = "Trang cuối",
                PageCountAndCurrentLocationFormat = "Page {0} of {1}.",
                ItemSliceAndTotalFormat = "Showing items {0} through {1} of {2}.",
                FunctionToDisplayEachPageNumber = null,
                ClassToApplyToFirstListItemInPager = null,
                ClassToApplyToLastListItemInPager = null,
                ContainerDivClasses = new[] { "pagination-container" },
                UlElementClasses = new[] { "pagination" },
                LiElementClasses = Enumerable.Empty<string>()
            };
            ViewBag.ship = ship;
            if (id != "")
            {
                ViewBag.idCate = id;
                ViewBag.idMenu = id;
            }
            else
            {
                
            }
            return PartialView(ListQuarantee.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult UpdateGuarantee(string id, string Active, string Ord)
        {
            if (ClsCheckRole.CheckQuyen(14, 2, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {

                int ids = int.Parse(id);
                var tblGuarantee = db.tblGuarantees.Find(ids);
                tblGuarantee.Active = bool.Parse(Active);
                tblGuarantee.Ord = int.Parse(Ord);
                db.SaveChanges();
                var result = string.Empty;
                result = "Thành công";
                return Json(new { result = result });
            }
            else
            {
                var result = string.Empty;
                result = "Bạn không có quyền thay đổi tính năng này";
                return Json(new { result = result });

            }

        }
        public ActionResult DeleteGuarantee(int id)
        {
            if (ClsCheckRole.CheckQuyen(14, 3, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                tblGuarantee tblGuarantee = db.tblGuarantees.Find(id);
                var result = string.Empty;
                db.tblGuarantees.Remove(tblGuarantee);
                db.SaveChanges();
                result = "Bạn đã xóa thành công.";
                return Json(new { result = result });
            }
            else
            {
                var result = string.Empty;
                result = "Bạn không có quyền thay đổi tính năng này";
                return Json(new { result = result });

            }
        }
        public ActionResult Create(int id,string idCate)
        {
            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            if (Session["Thongbao"] != null && Session["Thongbao"] != "")
            {

                ViewBag.thongbao = Session["Thongbao"].ToString();
                Session["Thongbao"] = "";
            }
            if (ClsCheckRole.CheckQuyen(14, 1, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                var pro = db.tblGuarantees.OrderByDescending(p => p.Ord).ToList();
                if (pro.Count > 0)
                    ViewBag.Ord = pro[0].Ord + 1;
                else
                { ViewBag.Ord = "0"; }
                List<SelectListItem> carlistDistrict = new List<SelectListItem>();
                var ListDistrict = db.tblDistricts.Where(m => m.Active == true).OrderBy(m => m.id).ToList();

                carlistDistrict.Clear();
                foreach (var item in ListDistrict)
                {
                    carlistDistrict.Add(new SelectListItem { Text = item.Name, Value = item.id.ToString() });
                }


                ViewBag.drDistrict = new SelectList(carlistDistrict, "Value", "Text", id);
                List<SelectListItem> carlistManu= new List<SelectListItem>();
                var ListManu = db.tblManufactures.Where(m => m.Active == true).OrderBy(m => m.id).ToList();

                carlistManu.Clear();
                foreach (var item in ListManu)
                {
                    carlistManu.Add(new SelectListItem { Text = item.Name, Value = item.id.ToString() });
                }
                if(idCate!=null && idCate !="")
                {
                    ViewBag.drManu = new SelectList(carlistManu, "Value", "Text", idCate);
                }
                else
                ViewBag.drManu = new SelectList(carlistManu, "Value", "Text");
                return View();
            }
            else
            {
                return Redirect("/Users/Erro");
            }
        }

        [HttpPost]
        [ValidateInput(false)]

        public ActionResult Create(tblGuarantee tblGuarantee, FormCollection collection,int id, int idCate)
        {
            int ids = int.Parse(collection["drDistrict"].ToString());
            int idCates = int.Parse(collection["drManu"].ToString());
            tblGuarantee.idDistrict = id;
            tblGuarantee.idManu = idCates;
            tblGuarantee.DateCreate = DateTime.Now;
            tblGuarantee.Tag = StringClass.NameToTag(tblGuarantee.Name);
            db.tblGuarantees.Add(tblGuarantee);
            db.SaveChanges();
            #region[Updatehistory]
            Updatehistoty.UpdateHistory("Add tblGuarantee", Request.Cookies["Username"].Values["FullName"].ToString(), Request.Cookies["Username"].Values["UserID"].ToString());

Loiloc/Views/Guaranteead/Index.cshtml
@{
    ViewBag.Title = "Danh sách bảo hành";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using PagedList.Mvc;
@model PagedList.IPagedList<Loiloc.Models.tblGuarantee>
@using Loiloc.Models;
@{
    string id = @Request.QueryString["id"].ToString();
}
<script type="text/javascript">
    $(function () {
        //$("input").keypress(function () {
      
        $("#drMenu").change(function () {
            //your code
            
            var idCate = $("#drMenu").val();
            $.post("/Guaranteead/partialGuarantee", {"id":@id,"idCate": idCate},
                function (data) {
                    $('#ajaxnhan').html(data);
                    $("#Create_Them").replaceWith("<a id='Create_Them' title='Thêm mới' class='toolbar btn btn-info btnCreate' href='../../Guaranteead/Create?id="+@id+"&idCate=" + idCate + "'><i class='icon-plus'></i>&nbsp;Thêm mới</a>");
                });

            //
        });
        $("#ddlPage").change(function () {
            //your code

            var pageSizes = $("#ddlPage").val();
            $.post("/Guaranteead/partialGuarantee", { "pageSizes": pageSizes },
                function (data) {
                    $('#ajaxnhan').html(data);
                });

            //
        });
        $(".alert").hide();
        $(".alert1").show();


    });

</script>
<script type="text/javascript">
    $(".alert").hide();
    $(".alert1").show();
    function SelectAllCheckboxes(chk) {
        $j('#cph_Main_ctl00_ctl00_grvProducts >tbody >tr >td:nth-child(1)').find("input:checkbox").attr('checked', chk.checked);
    }
    function CheckSelectAtLeastOne() {
        var checked = false;
        $j('#cph_Main_ctl00_ctl00_grvProducts >tbody >tr >td:nth-child(1)').find("input:checkbox").each(function() {
            if (this.checked) { checked = true; }
        });
        if (checked == false) {
            alert('Hãy chọn ít nhất 1  hạng mục để thao tác');
            return false;
        } else { return true; }
    }
    function ConfirmDelete() {
        if (CheckSelectAtLeastOne()) {
            var confirmAlert = 'Bạn có chắc chắn muốn xóa không?';
            $j('#cph_Main_ctl00_ctl00_grvProducts >tbody').find("tr").each(function() {
                var checked = false;
                var imgChecked = false;
                $j(this).find('img[src="http://st.hangtot.com/favicon.ico"]').each(function() {
                    imgChecked = true;
                });
                $j(this).find("input:checkbox:first").each(function() {
                    if (this.checked) { checked = true; }
                });
                if(checked == true && imgChecked == true)
                {
                    confirmAlert='Bạn có chắc chắn muốn xóa không'
                }
            });
            return confirm(confirmAlert);
        }
        return false;
    }


    function UpdateGuarantee(pId){

        var linkUpdateId = $j("#lbtUpdateProduct" + pId);
        var orderNumber = $j(linkUpdateId).closest('tr').children(".OrderNumber").children("#txtOrderNumber").val();

        var Active;
        if ($j(linkUpdateId).closest('tr').children(".Active").children("#Active:checked").is(':checked')) { Active = 'true'; }
        else { Active = 'false'; }

        var querystring = "{ 'id':'" + pId + "'," +
                            "'Ord':'" + orderNumber + "'," +
                            "'Active':'" + Active + "' }";

        $j.ajax({
            beforeSend: function() {},
            type: "POST",
            url: "/Guaranteead/UpdateGuarantee",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: querystring,
            success: function(response) {
                var result = response.result;
                if(result == "true"){  }
                else{
                    $(".alert").replaceWith("<div class='alert alert-info'>Bạn đã thay đổi "+result+"</div>");
                    $(".alert").fadeOut(2000);
                }
            }
        });

        return false;
    }
    function DeleteGuarantee(pId){
        if (confirm('Bạn có chắc chắn muốn xóa không ?')) {

            id = pId;
            var querystring = "{'id':'" + id + "'}";
            $j.ajax({
                beforeSend: function() {},
                type: "POST",
                url: "/Guaranteead/DeleteGuarantee",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: querystring,
                success: function(response) {
                    var result = response.result;
                    if(result == "true"){  }
                    else{
                        $(".alert").replaceWith("<div class='alert alert-info'>Bạn đã xóa thành công</div>");
                        $(".alert").fadeOut(5000);
                        location.reload();
                    }
                }
            });}

        return false;
    }
</script>
@using (Html.BeginForm())
{   @Html.ValidationSummary(true)
    <div class="container-fluid">
        <div style="width: 100%; margin: 0 auto;">
            <div id="Breadcrumb" class="Block Breadcrumb ui-widget-content ui-corner-top ui-corner-bottom">
                <ul>
                    <li class='SecondLast'><a href=""><i class="icon-home" style="font-size:14px;"></i> Trang chủ</a></li>
                    <li class='Last'><span>Danh sách địa chỉ bảo hành</span></li>
                </ul>
            </div>
            <div style="clear: both;"></div>
            <div id="cph_Main_ContentPane">
                <div class="widget">
                    <div class="widget-title">
                        <h4>Danh sách địa chỉ bảo hành</h4>

                        <div class="ui-widget-content ui-corner-top ui-corner-bottom">
                            <div id="toolbox">
                                <div style="float:right;" class="toolbox-content">
                                    <div id="msg" class="msg" style="float:left">
                                        <div class="alert alert-info" style="padding:0px" id="update-message">
                                        </div>
                                    </div>
                                    <table class="toolbar">
                                        <tr>
                                            <td align="center">
                                                <a id="Create_Them" title="Thêm mới" class="toolbar btn btn-info btnCreate" href="../../Guaranteead/Create?id=@Request.QueryString["id"].ToString()&id=&idCate=@ViewBag.idCate">
                                                    <i class="icon-plus"></i>&nbsp;
                                                    Thêm mới
                                                </a>
                                            </td>
                                            <td align="center">
                                                <button type="submit" class="toolbar btn btn-info" name="btnDelete" id="btnDelete"><i class="icon-trash"></i>&nbsp;Xóa</button>
                                            </td>
                                            <td align="center">
                                                <a id="cph_Main_ctl00_toolbox_rptAction_lbtAction_0" title="Trợ giúp" style="color:#FFF !important" class="toolbar btn btn-info" href="">
                                                    <i class="icon-question-sign"></i>&nbsp;
                                                    Trợ giúp
                                                </a>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div id="hiddenToolBarScroll" class="scrollBox hidden">
                            <h4>
                                <i class="icon-list-alt"></i>&nbsp;Danh sách địa chỉ bảo hành
                            </h4>
                            <div class="FloatMenuBar">

                                <div class="ui-widget-content ui-corner-top ui-corner-bottom">
                                    <div id="toolbox">
                                        <div style="float:right;" class="toolbox-content">
                                            <div id="msg" class="msg" style="float:left">
                                                <div class="alert alert-info" id="update-message">
                                                </div>
                                            </div>
                                            <table class="toolbar">
                                                <tr>

                                                    <td align="center">
                                                        <a id="Create_Them" title="Thêm mới" class="toolbar btn btn-info btnCreate" href="../../Guaranteead/Create?id=@Request.QueryString["id"].ToString()&idCate=@ViewBag.idCate">
                                                            <i class="icon-plus"></i>&nbsp;
                                                            Thêm mới
                                                        </a>
                                                    </td>

                                                    <td align="center">
                                                        <button type="submit" class="toolbar btn btn-info" name="btnDelete" id="btnDelete"><i class="icon-trash"></i>&nbsp;Xóa</button>

                                                    </td>
                                                    <td align="center">
                                                        <a id="cph_Main_ctl00_toolbox2_rptAction_lbtAction_0" title="Trợ giúp" style="color:#FFF !important" class="toolbar btn btn-info" href="">
                                                            <i class="icon-question-sign"></i>&nbsp;
                                                            Trợ giúp
                                                        </a>
                                                    </td>
                                                </tr>
                                            </table>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="widget-body">


                        <div>
                            <div class="row-fluid">
                                <div class="span3">
                                    <div id="sample_1_length" class="dataTables_length">
                                        <select name="ddlPage" id="ddlPage" style="width:160px;">
                                            <option value="10">10 Bản ghi / trang</option>
                                            <option selected="selected" value="20">20 Bản ghi / trang</option>
                                            <option value="30">30 Bản ghi / trang</option>
                                            <option value="50">50 Bản ghi / trang</option>
                                            <option value="100">100 Bản ghi / trang</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="span9 form-search pull-right text-right">


                                    <input name="txtSearch" type="search" maxlength="100" id="txtSearch" placeholder="Tên sản phẩm" style="width:200px;" />
                                    @Html.DropDownList("drMenu", "Hiển thị địa chỉ bảo hành")
                                    <input type="submit" name="ctl00$cph_Main$ctl00$ctl00$btnSearch" value="Tìm kiếm" id="cph_Main_ctl00_ctl00_btnSearch" class="btn" />
                                    <a class="btn " href="#"><i class="icon-filter"></i> Lọc tin tức</a>
                                </div>
                            </div>
                            <div id="cph_Main_ctl00_notification_divNotice" style="padding-top:10px;">
                                <!-- Messange -->
                                @Html.Raw(ViewBag.thongbao)

                                <!-- End Messange -->
                            </div>
                            @{Html.RenderAction("partialGuarantee", "Guaranteead");}



                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>



}

Loiloc/Views/Guaranteead/partialGuarantee.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Loiloc.Models.tblGuarantee>
@using Loiloc.Models
<div id="ajaxnhan">
    <table class="table table-striped table-bordered dataTable table-hover" cellspacing="0" id="cph_Main_ctl00_ctl00_grvProducts" style="border-collapse:collapse;">
        <tr>
            <th scope="col">
                <input id="cph_Main_ctl00_ctl00_grvProducts_chkAll" type="checkbox" name="ctl00$cph_Main$ctl00$ctl00$grvProducts$ctl01$chkAll" onclick="javascript:SelectAllCheckboxes(this);" />
            </th>
            <th scope="col">Tên địa chỉ bảo hành</th>
            <th scope="col">Số TT</th>
            <th scope="col">Kích hoạt</th>
            <th scope="col">Thao tác</th>
        </tr>
        @foreach (var item in Model)
        {
            if (item.Active == true)
            {
                <tr class="row0">
                    <td align="center" style="width:8px;">
                        <input id="chk_@item.id" type="checkbox" name="chk_@item.id" />

                    </td>
                    <td>
                        <a title="Sửa module @item.Name" href="../../Guaranteead/Edit?id=@item.id" id="@Html.Raw("lbtUpdateProduct")@item.id"> @item.Name <span style="color:red">(  @item.id )</span></a>
                    </td>
                    <td class="OrderNumber" align="center" style="width:45px;">
                        <input type="text" id="txtOrderNumber" style="width: 30px;" value="@item.Ord" onchange="javascript:return UpdateGuarantee(@item.id);" />
                    </td>
                    <td class="Active text-center" align="center" style="width:45px;">
                        @if (item.Active == true)
                        {
                            <input type="checkbox" id="Active" value="true" checked onchange="javascript:return UpdateGuarantee(@item.id);" />
                        }
                        else
                        {
                            <input type="checkbox" id="Active" value="false" onchange="javascript:return UpdateGuarantee(@item.id);" />
                        }
                    </td>

                    <td class="text-center" align="center" style="width:90px;">
                        <a class="action-link-button" title="Sửa tài khoản" href="../../Guaranteead/Edit?id=@item.id">
                            <i class="icon-edit"></i>
                        </a>
                        <a href="" class="action-link-button" id="@item.id" onclick="javascript:return DeleteGuarantee(@item.id);" title="Xóa sản danh mục">
                            <i class="icon-trash"></i>
                        </a>
                    </td>
                </tr>
            }
            else
            {
                <tr class="row0" style="opacity:0.2">
                    <td align="center" style="width:8px;">
                        <input id="chk_@item.id" type="checkbox" name="chk_@item.id" />

                    </td>
                    <td>
                        <a title="Sửa module @item.Name" href="../../Guaranteead/Edit?id=@item.id" id="@Html.Raw("lbtUpdateProduct")@item.id"> @item.Name <span style="color:red">(  @item.id )</span></a>
                    </td>
                    <td class="OrderNumber" align="center" style="width:45px;">
                        <input type="text" id="txtOrderNumber" style="width: 30px;" value="@item.Ord" onchange="javascript:return UpdateGuarantee(@item.id);" />
                    </td>
                    <td class="Active text-center" align="center" style="width:45px;">
                        @if (item.Active == true)
                        {
                            <input type="checkbox" id="Active" value="true" checked onchange="javascript:return UpdateGuarantee(@item.id);" />
                        }
                        else
                        {
                            <input type="checkbox" id="Active" value="false" onchange="javascript:return UpdateGuarantee(@item.id);" />
                        }
                    </td>

                    <td class="text-center" align="center" style="width:90px;">
                        <a class="action-link-button" title="Sửa tài khoản" href="../../Guaranteead/Edit?id=@item.id">
                            <i class="icon-edit"></i>
                        </a>
                        <a href="" class="action-link-button" id="@item.id" onclick="javascript:return DeleteGuarantee(@item.id);" title="Xóa sản danh mục">
                            <i class="icon-trash"></i>
                        </a>
                    </td>
                </tr>
            }

        }

    </table>
    <div class="pagination pagination-small pagination-right">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, idcate = @ViewBag.idcate, pageSizes = @ViewBag.pageSizes, sortOrder = ViewBag.CurrentSortOrder, sortName = ViewBag.CurrentSortName, sortLevel = ViewBag.CurrentSortLevel }), (PagedListRenderOptions)ViewBag.ship)
    </div>
</div>