Loiloc/Controllers/Admin/Images/ImagesadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Loiloc.Models;
using PagedList;
using PagedList.Mvc;
using System.Globalization;
using System.Web.UI.WebControls;
using System.Web.UI;
using System.IO;
using System.Xml;
using System.Data.Entity;
namespace Loiloc.Controllers.Admin.Images
{
    public class ImagesadController : Controller
    {
        List<SelectListItem> carlist = new List<SelectListItem>();

        // GET: Imagesad
        private LoilocContext db = new LoilocContext();

        // GET: Manufacturesad
        public ActionResult Index(string idCate, FormCollection collection)
        {
            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            if (ClsCheckRole.CheckQuyen(8, 0, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                var menuModel = db.tblGroupImages.Where(m => m.Active == true).OrderBy(m => m.id).ToList();
                carlist.Clear();
                foreach (var item in menuModel)
                {
                    carlist.Add(new SelectListItem { Text = item.Name, Value = item.id.ToString() });
                 }
                if (idCate != "")
                {

                    ViewBag.drMenu = new SelectList(carlist, "Value", "Text", idCate);
                    ViewBag.idCate = idCate;
                    ViewBag.idMenu = idCate;
                }
                else
                {
                    ViewBag.drMenu = carlist;
                }
                if (collection["btnDelete"] != null)
                {
                    foreach (string key in Request.Form.Keys)
                    {
                        var checkbox = "";
                        if (key.StartsWith("chk_"))
                        {
                            checkbox = Request.Form["" + key];
                            if (checkbox != "false")
                            {
                                if (ClsCheckRole.CheckQuyen(9, 3, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
                                {
                                    int id = Convert.ToInt32(key.Remove(0, 4));

                                    var tblimages = db.tblImages.Find(id);
                                    db.tblImages.Remove(tblimages);
                                    db.SaveChanges();
                                    
                                }
                                else
                                {
                                    return Redirect("/Users/Erro");

                                }
                            }
                        }
                    }
                    //dsd
                }
                if (Session["Thongbao"] != null && Session["Thongbao"] != "")
                {

                    ViewBag.thongbao = Session["Thongbao"].ToString();
                    Session["Thongbao"] = "";
                }
                return View();
            }
            else
            {
                return Redirect("/Users/Erro");

            }
        }
        public PartialViewResult partialImages(int? page, string text, string idCate, string pageSizes)
        {
            var ListImages = db.tblImages.OrderByDescending(p => p.Ord).ToList();

            int pageSize = 20;
            var pageNumber = (page ?? 1);
            // Thiết lập phân trang
            var ship = new PagedListRenderOptions
            {
                DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                DisplayLinkToLastPage = PagedListDisplayMode.Always,
                DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                DisplayLinkToNextPage = PagedListDisplayMode.Always,
                DisplayLinkToIndividualPages = true,
                DisplayPageCountAndCurrentLocation = false,
                MaximumPageNumbersToDisplay = 5,
                DisplayEllipsesWhenNotShowingAllPageNumbers = true,
                EllipsesFormat = "&#8230;",
                LinkToFirstPageFormat = "Trang đầu",
                LinkToPreviousPageFormat = "«",
                LinkToIndividualPageFormat = "{0}",
                LinkToNextPageFormat = "»",
                LinkToLastPageFormat = "Trang cuối",
                PageCountAndCurrentLocationFormat = "Page {0} of {1}.",
                ItemSliceAndTotalFormat = "Showing items {0} through {1} of {2}.",
                FunctionToDisplayEachPageNumber = null,
                ClassToApplyToFirstListItemInPager = null,
                ClassToApplyToLastListItemInPager = null,
                ContainerDivClasses = new[] { "pagination-container" },
                UlElementClasses = new[] { "pagination" },
                LiElementClasses = Enumerable.Empty<string>()
            };
            ViewBag.ship = ship;
            if (pageSizes != null)
            {
                ViewBag.pageSizes = pageSizes;
                pageSize = int.Parse(pageSizes.ToString());
                ViewBag.chuoicout = "<span style='color: #A52A2A;'>" + pageSize + "</span> / <span style='color: #333;'>" + ListImages.Count.ToString() + "</span>";
                return PartialView(ListImages.ToPagedList(pageNumber, pageSize));

            }
            if (idCate != "" && idCate != null)
            {
                int idmenu = int.Parse(idCate);

                ListImages = db.tblImages.Where(p => p.idCate == idmenu).OrderByDescending(m => m.Ord).ToList();
                ViewBag.Idcha = idCate;
                ViewBag.idCate = idCate;
                return PartialView(ListImages.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                ViewBag.Idcha = 0;
            }

            return PartialView(ListImages.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult UpdateImages(string id, string Ord, string ddlMenu, string Active)
        {
            if (ClsCheckRole.CheckQuyen(9, 2, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                int ids = int.Parse(id);
                int idcate = int.Parse(ddlMenu);
                var tblimages = db.tblImages.Find(ids);
                tblimages.Ord = int.Parse(Ord);
                tblimages.idCate = idcate;
                tblimages.Active = bool.Parse(Active);
                db.SaveChanges();
                var result = string.Empty;
                result = "Thành công";
                return Json(new { result = result });
            }
            else
            {
                var result = string.Empty;
                result = "Bạn không có quyền thay đổi tính năng này";
                return Json(new { result = result });
            }

        }
        public ActionResult DeleteImages(int id)
        {
            if (ClsCheckRole.CheckQuyen(9, 3, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                tblImage tblimages = db.tblImages.Find(id);
                var result = string.Empty;
                db.tblImages.Remove(tblimages);
                db.SaveChanges(); 
                result = "Bạn đã xóa thành công.";
                return Json(new { result = result });
            }
            else
            {
                var result = string.Empty;
                result = "Bạn không có quyền thay đổi tính năng này";
                return Json(new { result = result });
            }

        }
        public ActionResult AutoOrd(string idCate)
        {

            int id = int.Parse(idCate);
            var ListOrd = db.tblImages.Where(p => p.idCate == id).OrderByDescending(p => p.Ord).Take(1).ToList();
            var result = string.Empty;
            if (ListOrd.Count > 0)
            {
                int stt = int.Parse(ListOrd[0].Ord.ToString()) + 1;
                result = stt.ToString();
            }
            else
            {
                result = "0";

            }
            return Json(new { result = result });
        }
        public ActionResult Create(string id)
        {
            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            if (Session["Thongbao"] != null && Session["Thongbao"] != "")
            {

                ViewBag.thongbao = Session["Thongbao"].ToString();
                Session["Thongbao"] = "";
            }
            if (ClsCheckRole.CheckQuyen(8, 1, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                var menuModel = db.tblGroupProducts.Where(m => m.ParentID == null).OrderBy(m => m.id).ToList();
                carlist.Clear();
                string strReturn = "---";
                foreach (var item in menuModel)
                {
                    carlist.Add(new SelectListItem { Text = item.Name, Value = item.id.ToString() });
                    StringClass.DropDownListFor(item.id, carlist, strReturn);
                    strReturn = "---";
                }
                ViewBag.MutilMenu = new SelectList(carlist, "Value", "Text");

                
                
                var menuModels = db.tblGroupImages.Where(m => m.Active == true).OrderBy(m => m.Ord).ToList();
                var lstMenus = new List<SelectListItem>();
                lstMenus.Clear();
                foreach (var menu in menuModels)
                {
                    lstMenus.Add(new SelectListItem { Text = menu.Name, Value = menu.id.ToString() });

                }
                if (id != null && id != "")
                    ViewBag.drMenu = new SelectList(lstMenus, "Value", "Text", id);
                else
                    ViewBag.drMenu = lstMenus;



                var listCapacity = db.tblCapacities.OrderBy(m => m.id).ToList();

Loiloc/Views/Imagesad/Index.cshtml
@{
    ViewBag.Title = "Danh sách hình ảnh";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@using PagedList.Mvc;
@model PagedList.IPagedList<Loiloc.Models.tblImage>
@using Loiloc.Models;
<script type="text/javascript">
    $(function () {
        //$("input").keypress(function () {
        $("#drMenu").change(function () {
            //your code

            var idCate = $("#drMenu").val();
            $.post("/Imagesad/partialImages", { "idCate": idCate },
                function (data) {
                    $('#ajaxnhan').html(data);
                    $("#Create_Them").replaceWith("<a id='Create_Them' title='Thêm mới  ' class='toolbar btn btn-info btnCreate' href='../../Imagesad/Create?id=" + idCate + "'><i class='icon-plus'></i>&nbsp;Thêm mới </a>");
                    $("#Create_Product").replaceWith("<a id='Create_Product' title='Thêm mới' class='toolbar btn btn-info btnCreate' href='../../Imagesad/Create?id=" + idCate + "'><i class='icon-plus'></i>&nbsp;Thêm mới </a>");
                });

            //
        });
        $("#ddlPage").change(function () {
            //your code

            var pageSizes = $("#ddlPage").val();
            $.post("/Imagesad/partialImages", { "pageSizes": pageSizes },
                function (data) {
                    $('#ajaxnhan').html(data);
                });

            //
        });
        $(".alert").hide();

        $(".alert1").show();

    });

</script>
<script type="text/javascript">
    $(".alert").hide();
    $(".alert1").show();
    function SelectAllCheckboxes(chk) {
        $j('#cph_Main_ctl00_ctl00_grvProducts >tbody >tr >td:nth-child(1)').find("input:checkbox").attr('checked', chk.checked);
    }
    function CheckSelectAtLeastOne() {
        var checked = false;
        $j('#cph_Main_ctl00_ctl00_grvProducts >tbody >tr >td:nth-child(1)').find("input:checkbox").each(function () {
            if (this.checked) { checked = true; }
        });
        if (checked == false) {
            alert('Hãy chọn ít nhất 1 sản phẩm để thao tác');
            return false;
        } else { return true; }
    }
    function ConfirmDelete() {
        if (CheckSelectAtLeastOne()) {
            var confirmAlert = 'Bạn có chắc chắn muốn xóa không?';
            $j('#cph_Main_ctl00_ctl00_grvProducts >tbody').find("tr").each(function () {
                var checked = false;
                var imgChecked = false;
                $j(this).find('img[src="http://st.hangtot.com/favicon.ico"]').each(function () {
                    imgChecked = true;
                });
                $j(this).find("input:checkbox:first").each(function () {
                    if (this.checked) { checked = true; }
                });
                if (checked == true && imgChecked == true) {
                    confirmAlert = 'Bạn có chắc chắn muốn xóa không'
                }
            });
            return confirm(confirmAlert);
        }
        return false;
    }


    function UpdateImages(pId) {

        var linkUpdateId = $j("#lbtUpdateProduct" + pId);
        var orderNumber = $j(linkUpdateId).closest('tr').children(".OrderNumber").children("#txtOrderNumber").val();
        var ddlMenu = $j(linkUpdateId).closest('tr').children(".ddlMenu").children("#ddlMenu").val();
        var cbIsActive;
        if ($j(linkUpdateId).closest('tr').children(".Active").children("#cbIsActive:checked").is(':checked')) { cbIsActive = 'true'; }
        else { cbIsActive = 'false'; }
        var querystring = "{ 'id':'" + pId + "'," +
  "'Ord':'" + orderNumber + "'," + "'ddlMenu':'" + ddlMenu + "'," + "'Active':'" + cbIsActive + "' }";

        $j.ajax({
            beforeSend: function () { },
            type: "POST",
            url: "/Imagesad/UpdateImages",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: querystring,
            success: function (response) {
                var result = response.result;
                if (result == "true") { }
                else {
                    $(".alert").replaceWith("<div class='alert alert-info'>Bạn đã thay đổi " + result + "</div>");
                    $(".alert").fadeOut(2000);
                }
            }
        });

        return false;
    }
    function DeleteImages(pId) {
        if (confirm('Bạn có chắc chắn muốn xóa không ?')) {

            id = pId;
            var querystring = "{'id':'" + id + "'}";
            $j.ajax({
                beforeSend: function () { },
                type: "POST",
                url: "/Imagesad/DeleteImages",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: querystring,
                success: function (response) {
                    var result = response.result;
                    if (result == "true") { }
                    else {
                        $(".alert").replaceWith("<div class='alert alert-info'>Bạn đã xóa thành công</div>");
                        $(".alert").fadeOut(5000);
                        location.reload();
                    }
                }
            });
        }
        return false;
    }
</script>
@using (Html.BeginForm())
{   @Html.ValidationSummary(true)
<div class="container-fluid">
    <div style="width: 100%; margin: 0 auto;">
        <div id="Breadcrumb" class="Block Breadcrumb ui-widget-content ui-corner-top ui-corner-bottom">
            <ul>
                <li class='SecondLast'><a href=""><i class="icon-home" style="font-size:14px;"></i> Trang chủ</a></li>
                <li class='Last'><span>Danh sách hình ảnh</span></li>
            </ul>
        </div>
        <div style="clear: both;"></div>
        <div id="cph_Main_ContentPane">
            <div class="widget">
                <div class="widget-title">
                    <h4>Danh mục hình ảnh</h4>

                    <div class="ui-widget-content ui-corner-top ui-corner-bottom">
                        <div id="toolbox">
                            <div style="float:right;" class="toolbox-content">
                                <div id="msg" class="msg" style="float:left">
                                    <div class="alert alert-info" style="padding:0px" id="update-message">
                                    </div>
                                </div>
                                <table class="toolbar">
                                    <tr>
                                        <td align="center">
                                            <a id="Create_Them" title="Thêm mới" class="toolbar btn btn-info btnCreate" href="../../Imagesad/Create?id=@ViewBag.idCate ">
                                                <i class="icon-plus"></i>&nbsp;
                                                Thêm mới
                                            </a>
                                        </td>
                                        <td align="center">
                                            <button type="submit" class="toolbar btn btn-info" name="btnDelete" id="btnDelete"><i class="icon-trash"></i>&nbsp;Xóa</button>
                                        </td>
                                        <td align="center">
                                            <a id="cph_Main_ctl00_toolbox_rptAction_lbtAction_0" title="Trợ giúp"  style="color:#FFF !important" class="toolbar btn btn-info" href="">
                                                <i class="icon-question-sign"></i>&nbsp;
                                                Trợ giúp
                                            </a>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div id="hiddenToolBarScroll" class="scrollBox hidden">
                        <h4>
                            <i class="icon-list-alt"></i>&nbsp; Danh mục hình ảnh
                        </h4>
                        <div class="FloatMenuBar">

                            <div class="ui-widget-content ui-corner-top ui-corner-bottom">
                                <div id="toolbox">
                                    <div style="float:right;" class="toolbox-content">
                                        <div id="msg" class="msg" style="float:left">
                                            <div class="alert alert-info" id="update-message">
                                            </div>
                                        </div>
                                        <table class="toolbar">
                                            <tr>

                                                <td align="center">
                                                    <a id="Create_Them" title="Thêm mới" class="toolbar btn btn-info btnCreate" href="../../Imagesad/Create?id=@ViewBag.idCate">
                                                        <i class="icon-plus"></i>&nbsp;
                                                        Thêm mới
                                                    </a>
                                                </td>

                                                <td align="center">
                                                    <button type="submit" class="toolbar btn btn-info" name="btnDelete" id="btnDelete"><i class="icon-trash"></i>&nbsp;Xóa</button>

                                                </td>
                                                <td align="center">
                                                    <a id="cph_Main_ctl00_toolbox2_rptAction_lbtAction_0" title="Trợ giúp"  style="color:#FFF !important" class="toolbar btn btn-info" href="">
                                                        <i class="icon-question-sign"></i>&nbsp;
                                                        Trợ giúp
                                                    </a>
                                                </td>
                                            </tr>
                                        </table>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="widget-body">


                    <div>
                        <div class="row-fluid">
                            <div class="span3">
                                <div id="sample_1_length" class="dataTables_length">
                                    <select name="ddlPage" id="ddlPage" style="width:160px;">
                                        <option value="10">10 Bản ghi / trang</option>
                                        <option selected="selected" value="20">20 Bản ghi / trang</option>
                                        <option value="30">30 Bản ghi / trang</option>
                                        <option value="50">50 Bản ghi / trang</option>
                                        <option value="100">100 Bản ghi / trang</option>

                                    </select>
                                </div>
                            </div>
                            <div class="span9 form-search pull-right text-right">


                                @Html.DropDownList("drMenu", "Hiển thị tất danh mục")
                                <a class="btn " href="#"><i class="icon-filter"></i> Lọc danh mục con</a>
                            </div>
                        </div>
                        <div id="cph_Main_ctl00_notification_divNotice" style="padding-top:10px;">
                            <!-- Messange -->
                            @Html.Raw(ViewBag.thongbao)

                            <!-- End Messange -->
                        </div>
                        @{Html.RenderAction("partialImages", "Imagesad");}
                    </div>

                </div>
            </div>
        </div>

    </div>
</div>
}

Loiloc/Views/Imagesad/partialImages.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Loiloc.Models.tblImage>
@using Loiloc.Models
<div id="ajaxnhan">
    <div class="row-fluid">
        <div class="span3">
            <div style="margin-top:18px;">
                Tổng số ảnh: @Html.Raw(ViewBag.chuoicout)
            </div>
        </div>
        <div class="span9">
            <div class="pagination pagination-small pagination-right">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, idcate = @ViewBag.idcate, pageSizes = @ViewBag.pageSizes, sortOrder = ViewBag.CurrentSortOrder, sortName = ViewBag.CurrentSortName, sortLevel = ViewBag.CurrentSortLevel }), (PagedListRenderOptions)ViewBag.ship)
            </div>

        </div>
    </div>
    <table class="table table-striped table-bordered dataTable table-hover" cellspacing="0" id="cph_Main_ctl00_ctl00_grvProducts" style="border-collapse:collapse;">
        <tr>
            <th scope="col">
                <input id="cph_Main_ctl00_ctl00_grvProducts_chkAll" type="checkbox" name="ctl00$cph_Main$ctl00$ctl00$grvProducts$ctl01$chkAll" onclick="javascript:SelectAllCheckboxes(this);" />
            </th>
            <th scope="col">Hình ảnh</th>
            <th scope="col">Tên ảnh</th>
            <th scope="col">Nhóm ảnh</th>

            <th scope="col">Số TT</th>
            <th scope="col">Kích hoạt</th>
            <th scope="col">Thao tác</th>
        </tr>
        @foreach (var item in Model)
        {

            <tr class="row0">
                <td align="center" style="width:8px;">
                    <input id="chk_@item.id" type="checkbox" name="chk_@item.id" />

                </td>
                <td style="width:70px;">
                    <a title="Sửa module @item.Name" href="../../Imagesad/Edit?id=@item.id" id="@Html.Raw("lbtUpdateProduct")@item.id">

                        <img src="@item.Images" style=" max-height:60px" onerror="this.src='';" />
                    </a>
                </td>
                <td>
                    <a title="Sửa module @item.Name" href="../../Imagesad/Edit?id=@item.id" id="@Html.Raw("lbtUpdateProduct")@item.id">

                        @item.Name
                    </a>
                </td>
                <td class="ddlMenu" align="center" style="width:200px;">
                    @{
            LoilocContext db = new LoilocContext();
            var listpage = new List<SelectListItem>();
            var menuModel = db.tblGroupImages.OrderBy(m => m.Ord).ToList();
            var lstMenu = new List<SelectListItem>();
            lstMenu.Clear();
            foreach (var menu in menuModel)
            {
                lstMenu.Add(new SelectListItem { Text = menu.Name, Value = menu.id.ToString() });
            }
                    }
                    @Html.DropDownList(@item.idCate.ToString(), new SelectList(lstMenu, "Value", "Text", @item.idCate), "Lựa chọn danh mục", new { onchange = "javascript:return UpdateImages(" + item.id + ");", @Name = "ddlMenu", @id = "ddlMenu" })
                </td>

                <td class="OrderNumber" align="center" style="width:45px;">
                    <input type="text" id="txtOrderNumber" style="width: 30px;" value="@item.Ord" onchange="javascript:return UpdateImages(@item.id);" />
                </td>
                <td class="Active text-center" align="center" style="width:45px;">
                    @if (item.Active == true)
                    {
                        <input type="checkbox" id="cbIsActive" name="cbIsActive" value="true" checked onchange="javascript:return UpdateImages(@item.id);" />
                    }
                    else
                    {
                        <input type="checkbox" id="cbIsActive" name="cbIsActive" value="false" onchange="javascript:return UpdateImages(@item.id);" />
                    }
                </td>

                <td class="text-center" align="center" style="width:90px;">
                    <a class="action-link-button" title="Sửa" href="../../Imagesad/Edit?id=@item.id">
                        <i class="icon-edit"></i>
                    </a>
                    <a href="" class="action-link-button" id="@item.id" onclick="javascript:return DeleteImages(@item.id);" title="Xóa sản danh mục">
                        <i class="icon-trash"></i>
                    </a>
                </td>
            </tr>
        }

    </table>
    <div class="pagination pagination-small pagination-right">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, idcate = @ViewBag.idcate, pageSizes = @ViewBag.pageSizes, sortOrder = ViewBag.CurrentSortOrder, sortName = ViewBag.CurrentSortName, sortLevel = ViewBag.CurrentSortLevel }), (PagedListRenderOptions)ViewBag.ship)
    </div>
</div>