Loiloc/Controllers/Admin/Role/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Loiloc.Models;
using PagedList;
using PagedList.Mvc;
using System.Globalization;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
namespace Loiloc.Controllers.Admin.Role
{
    public class ModuleController : Controller
    {
        // GET: Module
        private LoilocContext db = new LoilocContext();
        public ActionResult Index(int? page, string id, FormCollection collection)
        {
            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            if (ClsCheckRole.CheckQuyen(3, 0, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                var ListModule = db.tblModules.ToList();

                const int pageSize = 20;
                var pageNumber = (page ?? 1);
                // Thiết lập phân trang
                var ship = new PagedListRenderOptions
                {
                    DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                    DisplayLinkToLastPage = PagedListDisplayMode.Always,
                    DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                    DisplayLinkToNextPage = PagedListDisplayMode.Always,
                    DisplayLinkToIndividualPages = true,
                    DisplayPageCountAndCurrentLocation = false,
                    MaximumPageNumbersToDisplay = 5,
                    DisplayEllipsesWhenNotShowingAllPageNumbers = true,
                    EllipsesFormat = "&#8230;",
                    LinkToFirstPageFormat = "Trang đầu",
                    LinkToPreviousPageFormat = "«",
                    LinkToIndividualPageFormat = "{0}",
                    LinkToNextPageFormat = "»",
                    LinkToLastPageFormat = "Trang cuối",
                    PageCountAndCurrentLocationFormat = "Page {0} of {1}.",
                    ItemSliceAndTotalFormat = "Showing items {0} through {1} of {2}.",
                    FunctionToDisplayEachPageNumber = null,
                    ClassToApplyToFirstListItemInPager = null,
                    ClassToApplyToLastListItemInPager = null,
                    ContainerDivClasses = new[] { "pagination-container" },
                    UlElementClasses = new[] { "pagination" },
                    LiElementClasses = Enumerable.Empty<string>()
                };
                ViewBag.ship = ship;
                if (Session["Thongbao"] != null && Session["Thongbao"] != "")
                {

                    ViewBag.thongbao = Session["Thongbao"].ToString();
                    Session["Thongbao"] = "";
                }
                if (collection["btnDelete"] != null)
                {
                    foreach (string key in Request.Form.Keys)
                    {
                        var checkbox = "";
                        if (key.StartsWith("chk_"))
                        {
                            checkbox = Request.Form["" + key];
                            if (checkbox != "false")
                            {
                                if (ClsCheckRole.CheckQuyen(3, 3, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
                                {
                                    int ids = Convert.ToInt32(key.Remove(0, 4));
                                    tblModule tblmodule = db.tblModules.Find(ids);
                                    db.tblModules.Remove(tblmodule);
                                    db.SaveChanges();
                                    return RedirectToAction("Index");
                                }
                                else
                                {
                                    return Redirect("/Users/Erro");

                                }
                            }
                        }
                    }
                }
                return View(ListModule.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return Redirect("/Users/Erro");

            }
        }
        public ActionResult UpdateModule(string id, string Active,string Ord)
        {
            if (ClsCheckRole.CheckQuyen(3, 2, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {

                int ids = int.Parse(id);
                var tblmodule = db.tblModules.Find(ids);
                tblmodule.Active = bool.Parse(Active);
                tblmodule.Ord = int.Parse(Ord);
                db.SaveChanges();
                var result = string.Empty;
                result = "Thành công";
                return Json(new { result = result });
            }
            else
            {
                var result = string.Empty;
                result = "Bạn không có quyền thay đổi tính năng này";
                return Json(new { result = result });

            }

        }
        public ActionResult DeleteModule(int id)
        {
            if (ClsCheckRole.CheckQuyen(3, 3, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                tblModule tblmodule = db.tblModules.Find(id);
                var result = string.Empty;
                db.tblModules.Remove(tblmodule);
                db.SaveChanges();
                result = "Bạn đã xóa thành công.";
                return Json(new { result = result });
            }
            else
            {
                var result = string.Empty;
                result = "Bạn không có quyền thay đổi tính năng này";
                return Json(new { result = result });

            }
        }
        public ActionResult Create()
        {
            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            if (Session["Thongbao"] != null && Session["Thongbao"] != "")
            {

                ViewBag.thongbao = Session["Thongbao"].ToString();
                Session["Thongbao"] = "";
            }
            if (ClsCheckRole.CheckQuyen(3, 1, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                var pro = db.tblModules.OrderByDescending(p => p.Ord).ToList();
                if (pro.Count > 0)
                    ViewBag.Ord = pro[0].Ord + 1;
                else
                { ViewBag.Ord = "0"; }
                return View();
            }
            else
            {
                return Redirect("/Users/Erro");
            }
        }

        [HttpPost]
        public ActionResult Create(tblModule tblmodule, FormCollection collection)
        {
           
                db.tblModules.Add(tblmodule);
                db.SaveChanges();
                #region[Updatehistory]
                Updatehistoty.UpdateHistory("Add User", Request.Cookies["Username"].Values["FullName"].ToString(), Request.Cookies["Username"].Values["UserID"].ToString());
                #endregion
                if (collection["btnSave"] != null)
                {
                    Session["Thongbao"] = "<div  class=\"alert alert-info alert1\">Bạn đã thêm thành công !<button class=\"close\" data-dismiss=\"alert\">×</button></div>";

                    return Redirect("/Module/Index");
                }
                if (collection["btnSaveCreate"] != null)
                {
                    Session["Thongbao"] = "<div  class=\"alert alert-info\">Bạn đã thêm thành công, mời bạn thêm danh mục  mới !<button class=\"close\" data-dismiss=\"alert\">×</button></div>";
                    return Redirect("/Module/Create");
                }
                return Redirect("Index");
          
 
        }
        public ActionResult Edit(int id = 0)
        {

            if ((Request.Cookies["Username"] == null))
            {
                return RedirectToAction("LoginIndex", "Login");
            }
            if (ClsCheckRole.CheckQuyen(3, 2, int.Parse(Request.Cookies["Username"].Values["UserID"])) == true)
            {
                tblModule tblmodule = db.tblModules.Find(id);
                if (tblmodule == null)
                {
                    return HttpNotFound();
                }
                return View(tblmodule);
            }
            else
            {
                return Redirect("/Users/Erro");


            }
        }

        //
        // POST: /Users/Edit/5

        [HttpPost]
        public ActionResult Edit(tblModule tblmodule, int id, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblmodule).State = EntityState.Modified;
              
                db.SaveChanges();
                #region[Updatehistory]
                Updatehistoty.UpdateHistory("Edit Module", Request.Cookies["Username"].Values["FullName"].ToString(), Request.Cookies["Username"].Values["UserID"].ToString());
                #endregion
                if (collection["btnSave"] != null)
                {
                    Session["Thongbao"] = "<div  class=\"alert alert-info alert1\">Bạn đã sửa  thành công !<button class=\"close\" data-dismiss=\"alert\">×</button></div>";

                    return Redirect("/Module/Index");
                }
                if (collection["btnSaveCreate"] != null)
                {
                    Session["Thongbao"] = "<div  class=\"alert alert-info\">Bạn đã thêm thành công, mời bạn thêm mới !<button class=\"close\" data-dismiss=\"alert\">×</button></div>";
                    return Redirect("/Module/Create");
                }
            }
            return View(tblmodule);
        }
    }
}

Loiloc/Views/Module/Create.cshtml
@{
    ViewBag.Title = "Thêm mới hạng mục";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@model Loiloc.Models.tblModule

@using (Html.BeginForm("Create", "Module", FormMethod.Post))
{   @Html.ValidationSummary(true)
    <div id="main-content">
        <div class="container-fluid">
            <div style="width: 100%; margin: 0 auto;">

                <div id="Breadcrumb" class="Block Breadcrumb ui-widget-content ui-corner-top ui-corner-bottom">
                    <ul>
                        <li><a href='/admin'><i class="icon-home" style="font-size:14px;"></i> Trang chủ</a></li>
                        <li class='SecondLast'><a href="/GroupProduct"> Hạng mục quyền</a></li>
                        <li class='Last'><span>Thêm mới hạng mục quyền</span></li>
                    </ul>
                </div>

                <div style="clear: both;"></div>

                <div id="cph_Main_ContentPane">
                    <div class="widget">
                        <!-- widget-title -->
                        <div class="widget-title">
                            <h4><i class="icon-reorder"></i>&nbsp;Thêm mới hạng mục quyền</h4>

                            <!-- Button -->
                            <div class="ui-widget-content ui-corner-top ui-corner-bottom">
                                <div id="toolbox">
                                    <div style="float:right;" class="toolbox-content">

                                        <table class="toolbar">
                                            <tr>

                                                <td align="center">
                                                    <button type="submit" class="toolbar btn btn-info" name="btnSave" id="btnSave"><i class="icon-save"></i> &nbsp;Lưu lại</button>

                                                </td>

                                                <td align="center">
                                                    <button type="submit" class="toolbar btn btn-info" name="btnSaveCreate" id="btnSaveCreate"><i class="icon-ok"></i> &nbsp;Lưu và Thêm mới</button>

                                                </td>
                                                <td align="center">
                                                    <a id="cph_Main_ctl00_toolbox_rptAction_lbtAction_4" title="Quay lại" style="color:#FFF !important" class="toolbar btn btn-info" href="">
                                                        <i class="icon-chevron-left"></i>&nbsp;
                                                        Quay lại
                                                    </a>
                                                </td>
                                                <td align="center">
                                                    <a onclick="" id="cph_Main_ctl00_toolbox_rptAction_lbtAction_0" title="Trợ giúp"  style="color:#FFF !important" class="toolbar btn btn-info" href="" )">
                                                        <i class="icon-question-sign"></i>&nbsp;
                                                        Trợ giúp
                                                    </a>
                                                </td>
                                            </tr>
                                        </table>

                                    </div>
                                </div>
                            </div>
                            <!-- End Button -->

                            <div id="hiddenToolBarScroll" class="scrollBox hidden">

                                <div class="FloatMenuBar" style="float:left; margin-left:20px">

                                    <div class="ui-widget-content ui-corner-top ui-corner-bottom">
                                        <div id="Div1">

                                            <div style="float:left;" class="toolbox-content">

                                                <table class="toolbar">
                                                    <tr>

                                                        <td align="center">
                                                            <button type="submit" class="toolbar btn btn-info" name="btnSave" id="btnSave"><i class="icon-save"></i> &nbsp;Lưu lại</button>

                                                        </td>

                                                        <td align="center">
                                                            <button type="submit" class="toolbar btn btn-info" name="btnSaveCreate" id="btnSaveCreate"><i class="icon-ok"></i> &nbsp;Lưu và Thêm mới</button>

                                                        </td>
                                                        <td align="center">
                                                            <a id="cph_Main_ctl00_toolbox_rptAction_lbtAction_4" title="Quay lại" style="color:#FFF !important" class="toolbar btn btn-info" href="">
                                                                <i class="icon-chevron-left"></i>&nbsp;
                                                                Quay lại
                                                            </a>
                                                        </td>
                                                        <td align="center">
                                                            <a onclick="" id="cph_Main_ctl00_toolbox_rptAction_lbtAction_0" title="Trợ giúp"  style="color:#FFF !important" class="toolbar btn btn-info" href="" )">
                                                                <i class="icon-question-sign"></i>&nbsp;
                                                                Trợ giúp
                                                            </a>
                                                        </td>
                                                    </tr>
                                                </table>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <!-- widget-title -->
                        <!-- widget-body -->
                        <div class="widget-body">
                            <div id="cph_Main_ctl00_notification_divNotice" style="padding-top:10px;">
                                <!-- Messange -->
                                @Html.Raw(ViewBag.thongbao)

                                <!-- End Messange -->
                            </div>
                            <table class="admintable" style="width: 100%;">
                                <tr>
                                    <td class="key">
                                        Tên hạng mục <span class="Required">*</span>
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(p => p.Name, new { @class = "Name_ad txtName", @autofocus = "autofocus", @required = "required" })


                                        <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                   Tên hạng muc quyền
                                                </p>
                                                <p class="tooltipmessage">
                                                    Tên hạng mục quyền (VD: Sản phẩm)
                                                </p>
                                            </span>
                                        </span>
                                        <span class="Aler_ttxtName" style="color: #F00"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="key">
                                        Thứ tự
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(p => p.Ord, new { @class = "Ord_ad", @Value = @Html.Raw(ViewBag.Ord) })


                                        <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                    Thứ tự hiển thị
                                                </p>
                                                <p class="tooltipmessage">
                                                    Thứ tự hiển thị  
                                                </p>
                                            </span>
                                        </span>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="key">
                                        Kích hoạt
                                    </td>
                                    <td>
                                        @{bool Active = true;}
                                        @Html.CheckBoxFor(model => Active)

                                        <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                    Hiển thị
                                                </p>
                                                <p class="tooltipmessage">
                                                    bạn có kích hoạt mục này này chạy hay không
                                                </p>
                                            </span>
                                        </span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}

Loiloc/Views/Module/Edit.cshtml
@{
    ViewBag.Title = "Sửa hạng mục";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@model Loiloc.Models.tblModule

@using (Html.BeginForm())
{   @Html.ValidationSummary(true)
    <div id="main-content">
        <div class="container-fluid">
            <div style="width: 100%; margin: 0 auto;">

                <div id="Breadcrumb" class="Block Breadcrumb ui-widget-content ui-corner-top ui-corner-bottom">
                    <ul>
                        <li><a href='/admin'><i class="icon-home" style="font-size:14px;"></i> Trang chủ</a></li>
                        <li class='SecondLast'><a href="/GroupProduct"> Hạng mục quyền</a></li>
                        <li class='Last'><span>Sửa hạng mục quyền</span></li>
                    </ul>
                </div>

                <div style="clear: both;"></div>

                <div id="cph_Main_ContentPane">
                    <div class="widget">
                        <!-- widget-title -->
                        <div class="widget-title">
                            <h4><i class="icon-reorder"></i>&nbsp;Sửa hạng mục quyền</h4>

                            <!-- Button -->
                            <div class="ui-widget-content ui-corner-top ui-corner-bottom">
                                <div id="toolbox">
                                    <div style="float:right;" class="toolbox-content">

                                        <table class="toolbar">
                                            <tr>

                                                <td align="center">
                                                    <button type="submit" class="toolbar btn btn-info" name="btnSave" id="btnSave"><i class="icon-save"></i> &nbsp;Lưu lại</button>

                                                </td>

                                                <td align="center">
                                                    <button type="submit" class="toolbar btn btn-info" name="btnSaveCreate" id="btnSaveCreate"><i class="icon-ok"></i> &nbsp;Lưu và Thêm mới</button>

                                                </td>
                                                <td align="center">
                                                    <a id="cph_Main_ctl00_toolbox_rptAction_lbtAction_4" title="Quay lại" style="color:#FFF !important" class="toolbar btn btn-info" href="">
                                                        <i class="icon-chevron-left"></i>&nbsp;
                                                        Quay lại
                                                    </a>
                                                </td>
                                                <td align="center">
                                                    <a onclick="" id="cph_Main_ctl00_toolbox_rptAction_lbtAction_0" title="Trợ giúp"  style="color:#FFF !important" class="toolbar btn btn-info" href="" )">
                                                        <i class="icon-question-sign"></i>&nbsp;
                                                        Trợ giúp
                                                    </a>
                                                </td>
                                            </tr>
                                        </table>

                                    </div>
                                </div>
                            </div>
                            <!-- End Button -->

                            <div id="hiddenToolBarScroll" class="scrollBox hidden">

                                <div class="FloatMenuBar" style="float:left; margin-left:20px">

                                    <div class="ui-widget-content ui-corner-top ui-corner-bottom">
                                        <div id="Div1">

                                            <div style="float:left;" class="toolbox-content">

                                                <table class="toolbar">
                                                    <tr>

                                                        <td align="center">
                                                            <button type="submit" class="toolbar btn btn-info" name="btnSave" id="btnSave"><i class="icon-save"></i> &nbsp;Lưu lại</button>

                                                        </td>

                                                        <td align="center">
                                                            <button type="submit" class="toolbar btn btn-info" name="btnSaveCreate" id="btnSaveCreate"><i class="icon-ok"></i> &nbsp;Lưu và Thêm mới</button>

                                                        </td>
                                                        <td align="center">
                                                            <a id="cph_Main_ctl00_toolbox_rptAction_lbtAction_4" title="Quay lại" style="color:#FFF !important" class="toolbar btn btn-info" href="">
                                                                <i class="icon-chevron-left"></i>&nbsp;
                                                                Quay lại
                                                            </a>
                                                        </td>
                                                        <td align="center">
                                                            <a onclick="" id="cph_Main_ctl00_toolbox_rptAction_lbtAction_0" title="Trợ giúp"  style="color:#FFF !important" class="toolbar btn btn-info" href="" )">
                                                                <i class="icon-question-sign"></i>&nbsp;
                                                                Trợ giúp
                                                            </a>
                                                        </td>
                                                    </tr>
                                                </table>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <!-- widget-title -->
                        <!-- widget-body -->
                        <div class="widget-body">
                            <div id="cph_Main_ctl00_notification_divNotice" style="padding-top:10px;">
                                <!-- Messange -->
                                @Html.Raw(ViewBag.thongbao)

                                <!-- End Messange -->
                            </div>
                            <table class="admintable" style="width: 100%;">
                                <tr>
                                    <td class="key">
                                        Tên hạng mục <span class="Required">*</span>
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(p => p.Name, new { @class = "Name_ad txtName", @autofocus = "autofocus", @required = "required" })


                                        <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                    Tên hạng muc quyền
                                                </p>
                                                <p class="tooltipmessage">
                                                    Tên hạng mục quyền (VD: Sản phẩm)
                                                </p>
                                            </span>
                                        </span>
                                        <span class="Aler_ttxtName" style="color: #F00"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="key">
                                        Thứ tự
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(p => p.Ord, new { @class = "Ord_ad"  })


                                        <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                    Thứ tự hiển thị
                                                </p>
                                                <p class="tooltipmessage">
                                                    Thứ tự hiển thị
                                                </p>
                                            </span>
                                        </span>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="key">
                                        Kích hoạt
                                    </td>
                                    <td>
                                        @{ bool Active = ((Model.Active == null) || (Model.Active == false)) ? false : true; }  
                                        @Html.CheckBoxFor(model => Active)


                                        <span class="tooltip-help">
                                            <span class="tooltipContent">
                                                <p class="tooltiptitle">
                                                    Hiển thị
                                                </p>
                                                <p class="tooltipmessage">
                                                    bạn có kích hoạt mục này này chạy hay không
                                                </p>
                                            </span>
                                        </span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}